<a href="https://colab.research.google.com/github/RajaShahzaibNaseer/DeepLearningPractice/blob/main/DeepLearningPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **These are the libraries which will be used to create the deep learning network.**

In [32]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


#**Introduction to Tensors**

##Creating Tensors

PyTorch tensors are created using torch.tensor() = https://pytorch.org/docs/stable/tensors.html
 following are a few types of tensors

###1. Scalar

In [33]:
scalar = torch.tensor(7)
scalar #this returns the scalar entity with a tensor datatype and its value indicating that it is a tensor

tensor(7)

In [34]:
scalar.ndim

0

In [35]:
# Get the tensor back as a python datatype
scalar.item()

7

###2. Vector

In [36]:
# Get tensor as a vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [37]:
vector.shape

torch.Size([2])

In [38]:
vector.ndim

1

###3. Matrix

In [39]:
#make a Matrix Tensor
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [40]:
MATRIX.ndim

2

In [41]:
MATRIX.shape

torch.Size([2, 2])

In [42]:
MATRIX[0][0]

tensor(7)

###4. Tensor

In [43]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [44]:
TENSOR.ndim

3

In [45]:
TENSOR.shape

torch.Size([1, 3, 3])

In [46]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

#Random Tensors
why random tensors?
random tensors are important because of the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`
Start with random numbers -> look at data -> update random numbers -> look at data -> update data
`



In [47]:
# create a random tensor:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3518, 0.0852, 0.3445, 0.8224],
        [0.9532, 0.1792, 0.6363, 0.1061],
        [0.0648, 0.1671, 0.3527, 0.7184]])

In [48]:
random_tensor.ndim

2

In [50]:
# Create a random tensor with the similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) #color channel, height, width
random_image_size_tensor

tensor([[[0.2037, 0.4161, 0.9114,  ..., 0.5567, 0.7492, 0.2428],
         [0.1824, 0.9058, 0.2290,  ..., 0.9229, 0.2268, 0.3102],
         [0.9969, 0.8595, 0.0516,  ..., 0.9303, 0.8329, 0.4155],
         ...,
         [0.1143, 0.8022, 0.7989,  ..., 0.6897, 0.7393, 0.8245],
         [0.6863, 0.3492, 0.4026,  ..., 0.2948, 0.4347, 0.3271],
         [0.5930, 0.2860, 0.4125,  ..., 0.8749, 0.6824, 0.1320]],

        [[0.7478, 0.9065, 0.9118,  ..., 0.1382, 0.4285, 0.7737],
         [0.4433, 0.9202, 0.1294,  ..., 0.5687, 0.1591, 0.8005],
         [0.8386, 0.6142, 0.3326,  ..., 0.2529, 0.0339, 0.5942],
         ...,
         [0.2154, 0.2946, 0.3357,  ..., 0.1222, 0.5931, 0.1757],
         [0.0332, 0.3316, 0.0440,  ..., 0.9793, 0.6776, 0.4330],
         [0.6587, 0.2958, 0.4151,  ..., 0.8400, 0.9817, 0.1022]],

        [[0.8696, 0.7363, 0.3324,  ..., 0.8545, 0.2321, 0.0043],
         [0.4893, 0.0686, 0.4233,  ..., 0.0531, 0.7075, 0.2151],
         [0.9009, 0.1459, 0.9308,  ..., 0.0342, 0.1015, 0.

In [51]:
random_image_size_tensor.ndim

3

In [53]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

#Zeros and ones

In [56]:
# Creating a tensor of all zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [58]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
# Creating a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [60]:
ones.dtype #the default datatype of tensors is float32

torch.float32

#Creating a range of tensors and tensors-like

###Range of tensors

In [63]:
torch.arange(0,10)
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
one_to_thousand = torch.arange(start = 0, end = 1000, step= 100)
one_to_thousand

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

###Range of tensor likes

In [68]:
#Creating tensors like: tensor likes are tensors that are similar to the shape of another tensor but have different values
tensor_like_zeroes = torch.zeros_like(input = one_to_ten)
tensor_like_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
tensor_like_ones = torch.ones_like(input=one_to_ten)
tensor_like_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#Tensor Datatypes

**Note** : Tensor datatypes is one of the 3 biggest errors that you'll run into when working with deep learning


1.   Tensors not in right datatype.
2.   Tensors not in right shape.
3.   Tensors not in right device



In [74]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # Datatype of the tensor being created (usually float32 or float16)
                               device = "cpu", # where the tensor is being executed (cpu for cpu and cuda for gpu)
                               requires_grad=False # whether you want pytorch to keep track of the gradients or not
                               )
float_32_tensor.dtype

torch.float32

In [75]:
float_16_tensor = torch.tensor([1,2,3],dtype=torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

#Getting Information from tensors
**Note** : Tensor datatypes is one of the 3 biggest errors that you'll run into when working with deep learning


1.   Tensors not in right datatype (use tensor.dtype)
2.   Tensors not in right shape. (use tensor.shape)
3.   Tensors not in right device (use tensor.device)


In [79]:
# creating a tensor and displaying its information:
random_tensor = torch.rand(3,4)
print(random_tensor)
print("datatype of tensor " + str(random_tensor.dtype))
print("shape of tensor " + str(random_tensor.shape))
print("device of tensor " + str(random_tensor.device))

tensor([[0.4046, 0.6939, 0.5799, 0.6226],
        [0.4206, 0.7148, 0.1799, 0.2845],
        [0.4457, 0.3918, 0.5456, 0.9775]])
datatype of tensor torch.float32
shape of tensor torch.Size([3, 4])
device of tensor cpu


#Manipulating Tensors (tensor operations)
tensor operations include
1. Addition
2. Subtraction
3. Multiplication (element wise)
4. Division
5. Matrix multiplication

In [84]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [85]:
tensor + 10

tensor([11, 12, 13])

In [86]:
tensor * 10

tensor([10, 20, 30])

In [87]:
tensor - 10

tensor([-9, -8, -7])

In [88]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

### Matrix multiplcation
There are two ways of performing multiplication in neural networking and deep learning
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two rules main that performing matrix multiplication needs to satisfy
1. the **inner dimensions** must match:
  * ` (3,2) @ (3,2) wont work`
  * ` (2,3) @ (3,2) will work`
  * ` (3,2) @ (2,3) will work`
2. The resulting matrix has the shape of the **outer dimensions**:
  * ` (2,3) @ (3,2) -> (2,2)`
  * ` (3,2) @ (2,3) -> (3,3)`

In [90]:
#element-wise multiplication for tensors
tensor * tensor

tensor([1, 4, 9])

In [89]:
# matrix multiplication for tensors using pyTorch
torch.matmul(tensor,tensor)

tensor(14)

#One of the most common errors in deep learning: shape errors

In [92]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues we can manipulate the shape of one of the tensors by using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [97]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [98]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [100]:
torch.matmul(tensor_A,tensor_B.T),torch.matmul(tensor_A,tensor_B.T).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

#Finding the min,max,mean,sum, etc (tensor aggregation)

In [103]:
#create a tensor
x = torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [104]:
x.min()

tensor(0)

In [105]:
x.max()

tensor(90)

In [108]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [109]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

#Finding the positional min and max (index of min and max)
we use argmin() and argmax() for this

In [113]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [114]:
x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

#Reshaping, stacking, squeezing and unsqueezin tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of a cetrain shape but keep the same memory as the original tensor
* stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensons from a tensor
* Unsqueeze - add a `1` dimension to a tensor
* Permute - return a view of the input with the dimensions permuted (swapped) in a certain way

In [116]:
# creating a tensor
y = torch.arange(1.,10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [119]:
#the new shape must be compatible with the number of elements in original tensor
y_reshaped = y.reshape(1,9)
y_reshaped , y_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [121]:
# change the view
z =y.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [124]:
# Changing z changes y because z is like a pointer to y
z[:,0] = 5
z, y

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [129]:
#stack tensors on top of each other
y_stacked = torch.stack([y,y,y,y], dim=1)
y_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [133]:
#squeeze removes a single dimension from a tensor
y_squeezed = y.squeeze(0)
y_squeezed, y_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [139]:
#unsqueeze adds a single dimension from tensor
y_unsqueezed = y_squeezed.unsqueeze(0)
y_unsqueezed, y_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [143]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(3,224,224))
x_permuted = x_original.permute(2,1,0)
x_original.shape, x_permuted.shape

(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

#PyTorch tensors and numpy
Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:
* `torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor.
* `torch.Tensor.numpy()` - PyTorch tensor -> NumPy array.